disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Aldair Cortés"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
secondaryLogo = "."
description = "This is my Aldair Cortes personal website"

["params.author"]
name = "Jorge Aldair Cortes Lopez"
bio = ""
